# Generated by Django 5.2.7 on 2025-10-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=70)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=100)),
                ('plec', models.CharField(choices=[('K', 'kobieta'), ('M', 'mezczyzna'), ('I', 'Inna')], default='I', max_length=1)),
                ('stanowsiko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.stanowisko')),
            ],
        ),
    ]
